name: Run UI tests

on:
  workflow_dispatch


jobs:
  run_tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
    
      - name: Setup Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test with pytest + create junit-report
        id: tests
        run: export PYTHONPATH=$(pwd) && pytest --junitxml "reports/junit-report.xml" "./tests"

      - name: TestRail CLI upload results
        if: always()
        run: |
          pip install trcli
          trcli -y \
            -h https://jesehik354354.testrail.io \
            --project "22_01_24" \
            -u ${{ secrets.USERNAME_TESTRAIL }} \
            -p ${{ secrets.PASSWORD_TESTRAIL }} \
            parse_junit \
            --title "Pytest Automated Test Run" \
            -f "reports/junit-report.xml"



         
    
